/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/mate-trabajado.glb --transform --types -o src/components/MateModel.tsx
Files: public/models/mate-trabajado.glb [69.36MB] > mate-trabajado-transformed.glb [5.9MB] (91%)
*/

"use client";

import * as THREE from "three";
import React from "react";
import { useGLTF } from "@react-three/drei";
import type { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    ["tripo_node_c12cde7c-5245-49a6-b4c1-9b3c614d4c16"]: THREE.Mesh;
  };
  materials: {
    ["tripo_material_c12cde7c-5245-49a6-b4c1-9b3c614d4c16"]: THREE.MeshStandardMaterial;
  };
};

const NODE_ID = "tripo_node_c12cde7c-5245-49a6-b4c1-9b3c614d4c16" as const;
const MATERIAL_ID =
  "tripo_material_c12cde7c-5245-49a6-b4c1-9b3c614d4c16" as const;

export function Model(props: React.JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/mate-trabajado-transformed.glb",
  ) as unknown as GLTFResult;

  const source = materials[MATERIAL_ID];
  const metalness = source.metalnessMap ? 1 : 0.6;

  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes[NODE_ID].geometry}>
        <meshStandardMaterial
          map={source.map}
          normalMap={source.normalMap}
          roughnessMap={source.roughnessMap}
          metalnessMap={source.metalnessMap}
          aoMap={source.aoMap}
          emissiveMap={source.emissiveMap}
          color="#ffffff"
          roughness={0.5}
          metalness={metalness}
          envMapIntensity={0.9}
          side={THREE.DoubleSide}
        />
      </mesh>
    </group>
  );
}

useGLTF.preload("/models/mate-trabajado-transformed.glb");
